### ISSUE TITLE
Default units ("miles") returns 0

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf-line-distance#4]
I'm using `turf.min.js` which may be out of date but:

```
turf.lineDistance(r.features[0], units="kilometers")
7.049512368675502
turf.lineDistance(r.features[0], units="miles")
4.380365444838383
turf.lineDistance(r.features[0])
0
```

Also, not sure if I'm reading the doco wrong, but shouldn't:

> turf.line-distance (Line, [units=miles])

be:

> turf.lineDistance (Line, [units="miles"])

**Comment by morganherlocker** [comment]
Thanks @stevage. There is currently no default unit, despite what the docs say. I'll update the docs or the code, depending on which people prefer.

I originally designed this to be a required parameter. Meters is pretty common, but my initial thinking in requiring the param is to avoid numeric overflows in careless code. For example, rough perimeter of the US:

![](https://dl.dropbox.com/s/qcywvofrrn3xizq/Screenshot%202015-02-11%2018.20.53.png?dl=0)

I could go either way on this.

**Comment by stevage** [comment]
Yeah, not sure. I assumed it would be metres, but I can sort of see why miles makes sense...if I try really hard. Requiring an explicit unit doesn't sound terrible. Maybe some kind of global config:

```
turf.setUnits("meters");
d = turf.lineDistance(line);
```

**Comment by morganherlocker** [comment]
hm, no globals like this in turf (would break modularity). I'll update the docs to make this required.

**Comment by lyzidiamond** [comment]
@morganherlocker if you can't get to this doc update, let me know and i'll take care of it tomorrow.
